name: CI fastAPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: install libraries
        run: |
          pip install --no-cache-dir --upgrade \
          --extra-index-url https://download.pytorch.org/whl/cpu \
          -r requirements.txt

      - name: Run Tests
        run: pytest
